# Generated by Django 5.1.4 on 2025-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolist_task_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, help_text='Write something about yourself.', max_length=500, null=True),
        ),
    ]
