# Generated by Django 5.1.4 on 2025-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
